[package]
name = 'Deployer'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = '24321bb83f308c1a45f11cdf59148c93ae946cb7'
subdir = 'aptos-move/framework/aptos-framework'

[dev-addresses]
deployer="0x277fa055b6a73c42c0662d5236c65c864ccbf2d4abd21f174a30c8b786eab84b"

[addresses]
deployer="_"
